spring:
  application:
    name: profy
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/profy
    username: postgres
    password: apolon2003
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
server:
  port: 8080